services:
  - type: web
    name: managebuddy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn projectname.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: projectname.settings
